# Config.pri file version 2.0. Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR = $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        } else {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }

    }

    CONFIG(release, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

simulator {
    CONFIG(debug, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

config_pri_assets {
    OTHER_FILES += \
        $$quote($$BASEDIR/assets/ExploreCategory.qml) \
        $$quote($$BASEDIR/assets/Favorite.qml) \
        $$quote($$BASEDIR/assets/Help.qml) \
        $$quote($$BASEDIR/assets/Home.qml) \
        $$quote($$BASEDIR/assets/ImagePreview.qml) \
        $$quote($$BASEDIR/assets/ImageUploader.qml) \
        $$quote($$BASEDIR/assets/LoginForm.qml) \
        $$quote($$BASEDIR/assets/PostMessage.qml) \
        $$quote($$BASEDIR/assets/PostRenderer.qml) \
        $$quote($$BASEDIR/assets/PrivateMessage.qml) \
        $$quote($$BASEDIR/assets/RefreshHeader.qml) \
        $$quote($$BASEDIR/assets/Search.qml) \
        $$quote($$BASEDIR/assets/SearchResult.qml) \
        $$quote($$BASEDIR/assets/Settings.qml) \
        $$quote($$BASEDIR/assets/SmileyPicker.qml) \
        $$quote($$BASEDIR/assets/SubCategoryPicker.qml) \
        $$quote($$BASEDIR/assets/SurveyHeader.qml) \
        $$quote($$BASEDIR/assets/ThreadPage.qml) \
        $$quote($$BASEDIR/assets/help/about_fr.html) \
        $$quote($$BASEDIR/assets/images/blackFace.png) \
        $$quote($$BASEDIR/assets/images/chickened.png) \
        $$quote($$BASEDIR/assets/images/default_avatar.png) \
        $$quote($$BASEDIR/assets/images/icon_BW.png) \
        $$quote($$BASEDIR/assets/images/icon_about.png) \
        $$quote($$BASEDIR/assets/images/icon_bold.png) \
        $$quote($$BASEDIR/assets/images/icon_bold.svg) \
        $$quote($$BASEDIR/assets/images/icon_bold_black.png) \
        $$quote($$BASEDIR/assets/images/icon_bottom.png) \
        $$quote($$BASEDIR/assets/images/icon_browse.png) \
        $$quote($$BASEDIR/assets/images/icon_category.png) \
        $$quote($$BASEDIR/assets/images/icon_code.png) \
        $$quote($$BASEDIR/assets/images/icon_code.svg) \
        $$quote($$BASEDIR/assets/images/icon_code_black.png) \
        $$quote($$BASEDIR/assets/images/icon_drap_lecture.gif) \
        $$quote($$BASEDIR/assets/images/icon_drap_lecture.png) \
        $$quote($$BASEDIR/assets/images/icon_drap_lecture.svg) \
        $$quote($$BASEDIR/assets/images/icon_drap_participe.gif) \
        $$quote($$BASEDIR/assets/images/icon_drap_participe.png) \
        $$quote($$BASEDIR/assets/images/icon_drap_participe.svg) \
        $$quote($$BASEDIR/assets/images/icon_favori.gif) \
        $$quote($$BASEDIR/assets/images/icon_favorite.png) \
        $$quote($$BASEDIR/assets/images/icon_favorite.svg) \
        $$quote($$BASEDIR/assets/images/icon_favorites.png) \
        $$quote($$BASEDIR/assets/images/icon_forum.png) \
        $$quote($$BASEDIR/assets/images/icon_global.gif) \
        $$quote($$BASEDIR/assets/images/icon_global.svg) \
        $$quote($$BASEDIR/assets/images/icon_global2.png) \
        $$quote($$BASEDIR/assets/images/icon_home.png) \
        $$quote($$BASEDIR/assets/images/icon_image.png) \
        $$quote($$BASEDIR/assets/images/icon_image_white.png) \
        $$quote($$BASEDIR/assets/images/icon_italic.png) \
        $$quote($$BASEDIR/assets/images/icon_italic_black.png) \
        $$quote($$BASEDIR/assets/images/icon_mp.png) \
        $$quote($$BASEDIR/assets/images/icon_next.png) \
        $$quote($$BASEDIR/assets/images/icon_next_all.png) \
        $$quote($$BASEDIR/assets/images/icon_pen.png) \
        $$quote($$BASEDIR/assets/images/icon_prev.png) \
        $$quote($$BASEDIR/assets/images/icon_prev_all.png) \
        $$quote($$BASEDIR/assets/images/icon_quote.png) \
        $$quote($$BASEDIR/assets/images/icon_quote.svg) \
        $$quote($$BASEDIR/assets/images/icon_quote_bis - copie.png) \
        $$quote($$BASEDIR/assets/images/icon_quote_bis.png) \
        $$quote($$BASEDIR/assets/images/icon_quote_bis.psd) \
        $$quote($$BASEDIR/assets/images/icon_quote_black.png) \
        $$quote($$BASEDIR/assets/images/icon_quoted.png) \
        $$quote($$BASEDIR/assets/images/icon_quoted_white.png) \
        $$quote($$BASEDIR/assets/images/icon_refresh - copie.png) \
        $$quote($$BASEDIR/assets/images/icon_refresh.png) \
        $$quote($$BASEDIR/assets/images/icon_settings.png) \
        $$quote($$BASEDIR/assets/images/icon_top.png) \
        $$quote($$BASEDIR/assets/images/icon_top.svg) \
        $$quote($$BASEDIR/assets/images/icon_underline.png) \
        $$quote($$BASEDIR/assets/images/icon_underline_black.png) \
        $$quote($$BASEDIR/assets/images/icon_write.png) \
        $$quote($$BASEDIR/assets/images/smiley/24.gif) \
        $$quote($$BASEDIR/assets/images/smiley/benetton.gif) \
        $$quote($$BASEDIR/assets/images/smiley/bic.gif) \
        $$quote($$BASEDIR/assets/images/smiley/biggrin.gif) \
        $$quote($$BASEDIR/assets/images/smiley/bug.gif) \
        $$quote($$BASEDIR/assets/images/smiley/calimero.gif) \
        $$quote($$BASEDIR/assets/images/smiley/confused.gif) \
        $$quote($$BASEDIR/assets/images/smiley/crazy.gif) \
        $$quote($$BASEDIR/assets/images/smiley/ddr555.gif) \
        $$quote($$BASEDIR/assets/images/smiley/dtc.gif) \
        $$quote($$BASEDIR/assets/images/smiley/eek.gif) \
        $$quote($$BASEDIR/assets/images/smiley/eek2.gif) \
        $$quote($$BASEDIR/assets/images/smiley/evil.gif) \
        $$quote($$BASEDIR/assets/images/smiley/foudtag.gif) \
        $$quote($$BASEDIR/assets/images/smiley/fouyaya.gif) \
        $$quote($$BASEDIR/assets/images/smiley/frown.gif) \
        $$quote($$BASEDIR/assets/images/smiley/fuck.gif) \
        $$quote($$BASEDIR/assets/images/smiley/gratgrat.gif) \
        $$quote($$BASEDIR/assets/images/smiley/gun.gif) \
        $$quote($$BASEDIR/assets/images/smiley/hap.gif) \
        $$quote($$BASEDIR/assets/images/smiley/hebe.gif) \
        $$quote($$BASEDIR/assets/images/smiley/hot.gif) \
        $$quote($$BASEDIR/assets/images/smiley/int.gif) \
        $$quote($$BASEDIR/assets/images/smiley/mad.gif) \
        $$quote($$BASEDIR/assets/images/smiley/miam.gif) \
        $$quote($$BASEDIR/assets/images/smiley/mmmfff.gif) \
        $$quote($$BASEDIR/assets/images/smiley/mouais.gif) \
        $$quote($$BASEDIR/assets/images/smiley/ohill.gif) \
        $$quote($$BASEDIR/assets/images/smiley/ohwell.gif) \
        $$quote($$BASEDIR/assets/images/smiley/ouimaitre.gif) \
        $$quote($$BASEDIR/assets/images/smiley/redface.gif) \
        $$quote($$BASEDIR/assets/images/smiley/smile.gif) \
        $$quote($$BASEDIR/assets/images/smiley/smilies/ange.gif) \
        $$quote($$BASEDIR/assets/images/smiley/smilies/bounce.gif) \
        $$quote($$BASEDIR/assets/images/smiley/smilies/cry.gif) \
        $$quote($$BASEDIR/assets/images/smiley/smilies/fou.gif) \
        $$quote($$BASEDIR/assets/images/smiley/smilies/heink.gif) \
        $$quote($$BASEDIR/assets/images/smiley/smilies/hello.gif) \
        $$quote($$BASEDIR/assets/images/smiley/smilies/jap.gif) \
        $$quote($$BASEDIR/assets/images/smiley/smilies/kaola.gif) \
        $$quote($$BASEDIR/assets/images/smiley/smilies/lol.gif) \
        $$quote($$BASEDIR/assets/images/smiley/smilies/love.gif) \
        $$quote($$BASEDIR/assets/images/smiley/smilies/na.gif) \
        $$quote($$BASEDIR/assets/images/smiley/smilies/non.gif) \
        $$quote($$BASEDIR/assets/images/smiley/smilies/ouch.gif) \
        $$quote($$BASEDIR/assets/images/smiley/smilies/pfff.gif) \
        $$quote($$BASEDIR/assets/images/smiley/smilies/pouah.gif) \
        $$quote($$BASEDIR/assets/images/smiley/smilies/pt1cable.gif) \
        $$quote($$BASEDIR/assets/images/smiley/smilies/sarcastic.gif) \
        $$quote($$BASEDIR/assets/images/smiley/smilies/sleep.gif) \
        $$quote($$BASEDIR/assets/images/smiley/smilies/sol.gif) \
        $$quote($$BASEDIR/assets/images/smiley/smilies/spamafote.gif) \
        $$quote($$BASEDIR/assets/images/smiley/smilies/sweat.gif) \
        $$quote($$BASEDIR/assets/images/smiley/smilies/wahoo.gif) \
        $$quote($$BASEDIR/assets/images/smiley/smilies/whistle.gif) \
        $$quote($$BASEDIR/assets/images/smiley/spookie.gif) \
        $$quote($$BASEDIR/assets/images/smiley/sum.gif) \
        $$quote($$BASEDIR/assets/images/smiley/tongue.gif) \
        $$quote($$BASEDIR/assets/images/smiley/vomi.gif) \
        $$quote($$BASEDIR/assets/images/smiley/wink.gif) \
        $$quote($$BASEDIR/assets/images/whiteFace.png) \
        $$quote($$BASEDIR/assets/images/whiteFace.svg) \
        $$quote($$BASEDIR/assets/images/whiteFace3.png) \
        $$quote($$BASEDIR/assets/main.qml) \
        $$quote($$BASEDIR/assets/model/AchatsVentes.xml) \
        $$quote($$BASEDIR/assets/model/Apple.xml) \
        $$quote($$BASEDIR/assets/model/Discussions.xml) \
        $$quote($$BASEDIR/assets/model/EmploiEtudes.xml) \
        $$quote($$BASEDIR/assets/model/Graphisme.xml) \
        $$quote($$BASEDIR/assets/model/Gsmgpspda.xml) \
        $$quote($$BASEDIR/assets/model/Hardware.xml) \
        $$quote($$BASEDIR/assets/model/HardwarePeripheriques.xml) \
        $$quote($$BASEDIR/assets/model/JeuxVideo.xml) \
        $$quote($$BASEDIR/assets/model/OSAlternatifs.xml) \
        $$quote($$BASEDIR/assets/model/OrdinateursPortables.xml) \
        $$quote($$BASEDIR/assets/model/OverclockingCoolingModding.xml) \
        $$quote($$BASEDIR/assets/model/Photonumerique.xml) \
        $$quote($$BASEDIR/assets/model/Programmation.xml) \
        $$quote($$BASEDIR/assets/model/Reseauxpersosoho.xml) \
        $$quote($$BASEDIR/assets/model/Setietprojetsdistribues.xml) \
        $$quote($$BASEDIR/assets/model/Systemereseauxpro.xml) \
        $$quote($$BASEDIR/assets/model/VideoSon.xml) \
        $$quote($$BASEDIR/assets/model/WindowsSoftware.xml) \
        $$quote($$BASEDIR/assets/model/listCategories.xml)
}

config_pri_source_group1 {
    SOURCES += \
        $$quote($$BASEDIR/src/ExploreCategoryController.cpp) \
        $$quote($$BASEDIR/src/Globals.cpp) \
        $$quote($$BASEDIR/src/HubIntegration.cpp) \
        $$quote($$BASEDIR/src/ImageUploaderController.cpp) \
        $$quote($$BASEDIR/src/ListFavoriteController.cpp) \
        $$quote($$BASEDIR/src/LoginController.cpp) \
        $$quote($$BASEDIR/src/Network/CookieJar.cpp) \
        $$quote($$BASEDIR/src/Network/HFRNetworkAccessManager.cpp) \
        $$quote($$BASEDIR/src/Network/NetImageTracker.cpp) \
        $$quote($$BASEDIR/src/Network/WebResourceManager.cpp) \
        $$quote($$BASEDIR/src/PostMessageController.cpp) \
        $$quote($$BASEDIR/src/PrivateMessageController.cpp) \
        $$quote($$BASEDIR/src/SearchController.cpp) \
        $$quote($$BASEDIR/src/SearchKeyRetriever.cpp) \
        $$quote($$BASEDIR/src/Settings.cpp) \
        $$quote($$BASEDIR/src/ShowThreadController.cpp) \
        $$quote($$BASEDIR/src/SmileyPickerController.cpp) \
        $$quote($$BASEDIR/src/applicationui.cpp) \
        $$quote($$BASEDIR/src/main.cpp)

    HEADERS += \
        $$quote($$BASEDIR/src/DataObjects.h) \
        $$quote($$BASEDIR/src/ExploreCategoryController.hpp) \
        $$quote($$BASEDIR/src/Globals.h) \
        $$quote($$BASEDIR/src/HubIntegration.h) \
        $$quote($$BASEDIR/src/ImageUploaderController.hpp) \
        $$quote($$BASEDIR/src/ListFavoriteController.hpp) \
        $$quote($$BASEDIR/src/LoginController.hpp) \
        $$quote($$BASEDIR/src/Network/CookieJar.hpp) \
        $$quote($$BASEDIR/src/Network/HFRNetworkAccessManager.hpp) \
        $$quote($$BASEDIR/src/Network/NetImageTracker.h) \
        $$quote($$BASEDIR/src/Network/WebResourceManager.h) \
        $$quote($$BASEDIR/src/PostMessageController.hpp) \
        $$quote($$BASEDIR/src/PrivateMessageController.hpp) \
        $$quote($$BASEDIR/src/SearchController.hpp) \
        $$quote($$BASEDIR/src/SearchKeyRetriever.hpp) \
        $$quote($$BASEDIR/src/Settings.hpp) \
        $$quote($$BASEDIR/src/ShowThreadController.hpp) \
        $$quote($$BASEDIR/src/SmileyPickerController.hpp) \
        $$quote($$BASEDIR/src/applicationui.hpp)
}

INCLUDEPATH += $$quote($$BASEDIR/src/Network) \
    $$quote($$BASEDIR/src)

CONFIG += precompile_header

PRECOMPILED_HEADER = $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES += \
        $$quote($$BASEDIR/../src/*.c) \
        $$quote($$BASEDIR/../src/*.c++) \
        $$quote($$BASEDIR/../src/*.cc) \
        $$quote($$BASEDIR/../src/*.cpp) \
        $$quote($$BASEDIR/../src/*.cxx) \
        $$quote($$BASEDIR/../src/Network/*.c) \
        $$quote($$BASEDIR/../src/Network/*.c++) \
        $$quote($$BASEDIR/../src/Network/*.cc) \
        $$quote($$BASEDIR/../src/Network/*.cpp) \
        $$quote($$BASEDIR/../src/Network/*.cxx) \
        $$quote($$BASEDIR/../assets/*.qml) \
        $$quote($$BASEDIR/../assets/*.js) \
        $$quote($$BASEDIR/../assets/*.qs) \
        $$quote($$BASEDIR/../assets/help/*.qml) \
        $$quote($$BASEDIR/../assets/help/*.js) \
        $$quote($$BASEDIR/../assets/help/*.qs) \
        $$quote($$BASEDIR/../assets/images/*.qml) \
        $$quote($$BASEDIR/../assets/images/*.js) \
        $$quote($$BASEDIR/../assets/images/*.qs) \
        $$quote($$BASEDIR/../assets/images/smiley/*.qml) \
        $$quote($$BASEDIR/../assets/images/smiley/*.js) \
        $$quote($$BASEDIR/../assets/images/smiley/*.qs) \
        $$quote($$BASEDIR/../assets/images/smiley/smilies/*.qml) \
        $$quote($$BASEDIR/../assets/images/smiley/smilies/*.js) \
        $$quote($$BASEDIR/../assets/images/smiley/smilies/*.qs) \
        $$quote($$BASEDIR/../assets/model/*.qml) \
        $$quote($$BASEDIR/../assets/model/*.js) \
        $$quote($$BASEDIR/../assets/model/*.qs)

    HEADERS += \
        $$quote($$BASEDIR/../src/*.h) \
        $$quote($$BASEDIR/../src/*.h++) \
        $$quote($$BASEDIR/../src/*.hh) \
        $$quote($$BASEDIR/../src/*.hpp) \
        $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS = $$quote($${TARGET}_fr_FR.ts) \
    $$quote($${TARGET}.ts)
